# Python Cheat Sheet

The following content is taken from http://www.ias.u-psud.fr/pperso/aboucaud/python/cheatsheet.html

This cheat sheet should serve as a short refresher to everybody who hasn't used Python for some time.

## Pure Python

### Types

In [1]:
a = 2           # integer
b = 5.0         # float
c = 8.3e5       # exponential
d = 1.5 + 0.5j  # complex
e = 4 > 5       # boolean
f = 'word'      # string

### Lists

In [2]:
a = ['red', 'blue', 'green']      # manually initialization
b = range(5)                      # initialization through a function
c = [nu**2 for nu in b]           # initialize through list comprehension
d = [nu**2 for nu in b if nu < 3]  # list comprehension with condition
e = c[0]                          # access element
f = c[1:2]                       # access a slice of the list
g = ['re', 'bl'] + ['gr']         # list concatenation
h = ['re'] * 5                    # repeat a list
['re', 'bl'].index('re')          # returns index of 're'
're' in ['re', 'bl']              # true if 're' in list
sorted([3, 2, 1])                 # returns sorted list
z = ['red'] + ['green', 'blue']   # list concatenation

### Dictionaries

In [3]:
a = {'red': 'rouge', 'blue': 'bleu', 'green': 'vert'}  # dictionary
b = a['red']                                           # translate item
c = [value for key, value in a.items()]                # loop through contents
d = a.get('yellow', 'no translation found')            # return default

### Strings

In [4]:
a = 'red'                      # assignment
char = a[2]                    # access individual characters
'red ' + 'blue'                # string concatenation
'1, 2, three'.split(',')       # split string into list
'.'.join(['1', '2', 'three'])  # concatenate list into string

'1.2.three'

### Operators

In [5]:
a = 2             # assignment
b = [2,3]
a += 1    # change and assign, try also `*=` and `/=`
3 + 2             # addition
3 / 2             # integer division (python2) or float division (python3)
3 // 2            # integer division
3 * 2             # multiplication
3 ** 2            # exponent
3 % 2             # remainder
abs(-3)             # absolute value
1 == 1            # equal
2 > 1             # larger
2 < 1             # smaller
1 != 2            # not equal
1 != 2 and 2 < 3  # logical AND
1 != 2 or 2 < 3   # logical OR
not 1 == 2        # logical NOT
a in b            # test if a is in b
a is b            # test if objects point to the same memory (id)

False

### Control Flow

In [6]:
# if/elif/else
a, b = 1, 2
if a + b == 3:
    print ('True')
elif a + b == 1:
    print ('False')
else:
    print ('?')

# for
a = ['red', 'blue', 'green']
for color in a:
    print (color)

# while
number = 1
while number < 10:
    print (number)
    number += 1

# break
number = 1
while True:
    print (number)
    number += 1
    if number > 10:
        break

# continue
for i in range(20):
    if i % 2 == 0:
        continue
    print (i)

True
red
blue
green
1
2
3
4
5
6
7
8
9
1
2
3
4
5
6
7
8
9
10
1
3
5
7
9
11
13
15
17
19


### Functions, Classes, Generators, Decorators

In [7]:
# Function
def myfunc(a1, a2):
    return a1 * a2

a1, a2 = 4, 5
x = myfunc(a1,a2)

# Class
class Point(object):
    def __init__(self, x):
        self.x = x
    def __call__(self):
        print (self.x)

x = Point(3)

# Generators
def firstn(n):
    num = 0
    while num < n:
        yield num
        num += 1

# consume the generator with list comprehension
x = [i for i in firstn(10)]

# Decorators
class myDecorator(object):
    def __init__(self, f):
        self.f = f
    def __call__(self):
        print ("call")
        self.f()

@myDecorator
def my_funct():
    print ('func')

my_funct()

call
func


## IPython

### Python console

<object>?  # Information about the object
<object>.<TAB>  # tab completion

# measure runtime of a function:
%timeit range(1000)
100000 loops, best of 3: 7.76 us per loop

# run scripts and debug
%run
%run -d  # run in debug mode
%run -t  # measures execution time
%run -p  # runs a profiler
%debug  # jumps to the debugger after an exception

%pdb  # run debugger automatically on exception

# examine history
%history
%history ~1/1-5  # lines 1-5 of last session

# run shell commands
!make  # prefix command with "!"

# clean namespace
%reset

### Debugger commands

n  # execute next line

## NumPy (import numpy as np)

### array initialization

In [10]:
import numpy as np

In [11]:
np.array([2, 3, 4])             # direct initialization
np.empty(20, dtype=np.float32)  # single precision array with 20 entries
np.zeros(200)                   # initialize 200 zeros
np.ones((3,3), dtype=np.int32)  # 3 x 3 integer matrix with ones
np.eye(200)                     # ones on the diagonal
np.zeros_like(a)                # returns array with zeros and the shape of a
np.linspace(0., 10., 100)       # 100 points from 0 to 10
np.arange(0, 100, 2)            # points from 0 to <100 with step width 2
np.logspace(-5, 2, 100)         # 100 log-spaced points between 1e-5 and 1e2
a = np.array([[2, 3], [4, 5]])     
np.copy(a)                      # copy array to new memory

array([[2, 3],
       [4, 5]])

### reading/ writing files

np.fromfile(fname/object, dtype=np.float32, count=5)  # read binary data from file
np.loadtxt(fname/object, skiprows=2, delimiter=',')   # read ascii data from file

### array properties and operations

In [13]:
a.shape                # a tuple with the lengths of each axis
len(a)                 # length of axis 0
a.ndim                 # number of dimensions (axes)
a.sort(axis=1)         # sort array along axis
a.flatten()            # collapse array to one dimension
a.conj()               # return complex conjugate
a.astype(np.int16)     # cast to integer
np.argmax(a, axis=0)   # return index of maximum along a given axis
np.cumsum(a)           # return cumulative sum
np.any(a)              # True if any element is True
np.all(a)              # True if all elements are True
np.argsort(a, axis=1)  # return sorted index array along axis

array([[0, 1],
       [0, 1]])

### indexing

In [14]:
a = np.arange(100)          # initialization with 0 - 99
a[: 3] = 0                  # set the first three indices to zero
a[1: 5] = 1                 # set indices 1-4 to 1
start, stop, step = 10, 20, 2
a[start:stop:step]          # general form of indexing/slicing
a[None, :]                  # transform to column vector
a[[1, 1, 3, 8]]             # return array with values of the indices
a = a.reshape(10, 10)       # transform to 10 x 10 matrix
a.T                         # return transposed view
np.transpose(a, (1, 0))  # transpose array to new axis order
a[a < 2]                    # returns array that fulfills element-wise condition

array([0, 1, 1, 1, 1])

### boolean arrays

In [15]:
a, b = np.arange(100), 6 * np.arange(100)
a < 2                          # returns array with boolean values
np.logical_and(a < 2, b > 10)  # element-wise logical and
np.logical_or(a < 2, b > 10)   # element-wise logical or
~a                             # invert boolean array
np.invert(a)                   # invert boolean array

array([  -1,   -2,   -3,   -4,   -5,   -6,   -7,   -8,   -9,  -10,  -11,
        -12,  -13,  -14,  -15,  -16,  -17,  -18,  -19,  -20,  -21,  -22,
        -23,  -24,  -25,  -26,  -27,  -28,  -29,  -30,  -31,  -32,  -33,
        -34,  -35,  -36,  -37,  -38,  -39,  -40,  -41,  -42,  -43,  -44,
        -45,  -46,  -47,  -48,  -49,  -50,  -51,  -52,  -53,  -54,  -55,
        -56,  -57,  -58,  -59,  -60,  -61,  -62,  -63,  -64,  -65,  -66,
        -67,  -68,  -69,  -70,  -71,  -72,  -73,  -74,  -75,  -76,  -77,
        -78,  -79,  -80,  -81,  -82,  -83,  -84,  -85,  -86,  -87,  -88,
        -89,  -90,  -91,  -92,  -93,  -94,  -95,  -96,  -97,  -98,  -99,
       -100])

### element-wise operations and math functions

In [16]:
y, x = np.arange(10), np.arange(10)
a * 5              # multiplication with scalar
a + 5              # addition with scalar
a + b              # addition with array b
a / b              # division with b (np.NaN for division by zero)
np.exp(a)          # exponential (complex and real)
np.power(a,b)      # a to the power b
np.sin(a)          # sine
np.cos(a)          # cosine
np.arctan2(y,x)    # arctan(y/x)
np.arcsin(x)       # arcsin
np.radians(a)      # degrees to radians
np.degrees(a)      # radians to degrees
np.var(a)          # variance of array
np.std(a, axis=0)  # standard deviation

/opt/conda/lib/python3.5/site-packages/ipykernel/__main__.py:5: RuntimeWarning: invalid value encountered in true_divide
/opt/conda/lib/python3.5/site-packages/ipykernel/__main__.py:7: RuntimeWarning: overflow encountered in power
/opt/conda/lib/python3.5/site-packages/ipykernel/__main__.py:7: RuntimeWarning: invalid value encountered in power
/opt/conda/lib/python3.5/site-packages/ipykernel/__main__.py:11: RuntimeWarning: invalid value encountered in arcsin


28.866070047722118

### inner / outer products

In [17]:
a, b = np.array([[2, 3], [4, 5]]), np.array([[20, 30], [40, 50]])
np.dot(a, b)                        # inner matrix product: a_mi b_in
np.einsum('ik,kl->il', a, b)        # einstein summation convention
np.sum(a, axis=1)                   # sum over axis 1
np.abs(a)                           # return array with absolute values
a[None, :] + b[:, None]             # outer sum
a[None, :] * b[:, None]             # outer product
np.outer(a, b)                      # outer product
np.sum(a * a.T)                     # matrix norm

53

### interpolation, integration

In [24]:
np.trapz(y, x=None, dx=1.0, axis=0) # integrate along axis 0
np.interp(x=2.5, xp=[1, 2, 3], fp=[3, 2, 0])      # interpolate function xp, yp at points x

1.0

### fft

In [30]:
np.fft.fft(y)             # complex fourier transform of y
freqs = np.fft.fftfreq(len(y))   # fft frequencies for a given length
np.fft.fftshift(freqs)    # shifts zero frequency to the middle
np.fft.rfft(y)            # real fourier transform of y
np.fft.rfftfreq(len(y))  # real fft frequencies for a given length

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5])

### rounding

In [31]:
a=3.56
np.ceil(a)   # rounds to nearest upper int
np.floor(a)  # rounds to nearest lower int
np.round(a)  # rounds to neares int

4.0

### random variables

In [32]:
np.random.normal(loc=0, scale=2, size=100)  # 100 normal distributed random numbers
np.random.seed(23032)                       # resets the seed value
np.random.rand(200)                         # 200 random numbers in [0, 1)
np.random.uniform(1, 30, 200)               # 200 random numbers in [1, 30)
np.random.random_integers(1, 15, 300)       # 300 random integers between [1, 15]

/opt/conda/lib/python3.5/site-packages/ipykernel/__main__.py:5: DeprecationWarning: This function is deprecated. Please call randint(1, 15 + 1) instead


array([ 8,  9,  3,  9,  2, 15,  3,  2,  3,  2,  8, 11,  1,  2, 14, 13,  3,
        3, 13,  7,  3, 13, 15,  7, 10,  3, 15, 10,  2,  2,  8, 12, 10,  5,
       13, 12, 11, 15,  1, 12,  7,  4,  1, 10, 13,  7,  5, 14,  8, 14, 14,
       15,  8, 14,  4, 11,  5,  7,  5, 12,  7,  1,  5,  7, 14, 14, 10, 12,
       13, 12,  7, 15, 13,  3, 12,  7,  6,  2, 11,  8, 10,  1, 14, 10, 13,
        2, 12,  1,  6, 12,  9,  4,  9,  4,  3,  7, 13, 14, 10,  2,  3,  8,
        1, 10,  4,  5,  3,  1,  4, 10,  6, 14,  2, 14,  1,  6,  3, 11,  1,
        4, 14,  7,  2,  9,  3,  7,  6,  7,  4,  2,  9, 13, 12,  3,  4, 10,
        2,  5, 10, 11, 14,  9, 10,  7,  2, 10,  6, 14,  7,  3,  2, 13,  9,
        4, 10,  4,  3,  7,  3, 15,  7, 12,  5, 13,  9,  2, 10, 11,  2,  1,
       15, 15,  5,  5,  8,  3,  2,  1, 14,  1, 10, 12,  7,  1,  5,  7, 13,
        3,  9,  9,  8,  6,  4,  3, 11,  4,  3,  8,  6, 11, 12,  2,  1,  1,
       13,  5, 14, 12, 12, 10,  7, 12,  4,  9,  2, 12,  9,  9,  6,  8,  2,
        9,  8,  4, 10,  9

## Matplotlib (import matplotlib.pyplot as plt)

### figures and axes

In [35]:
import matplotlib.pyplot as plt

In [36]:
fig = plt.figure(figsize=(5, 2), facecolor='black')  # initialize figure
ax = fig.add_subplot(3, 2, 2)                        # add second subplot in a 3 x 2 grid
fig, axes = plt.subplots(5, 2, figsize=(5, 5))       # return fig and array of axes in a 5 x 2 grid
ax = fig.add_axes(left=.3, bottom=.1, width=.6, height=.8)     # manually add axes at a certain position

### figures and axes properties

fig.suptitle('title')            # big figure title
fig.subplots_adjust(bottom=0.1,
                    right=0.8,
                    top=0.9,
                    wspace=0.2,
                    hspace=0.5)  # adjust subplot positions
fig.tight_layout(pad=0.1,
                 h_pad=0.5,
                 w_pad=0.5,
                 rect=None)      # adjust subplots to fit perfectly into fig
ax.set_xlabel()                  # set xlabel
ax.set_ylabel()                  # set ylabel
ax.set_xlim(1, 2)                # sets x limits
ax.set_ylim(3, 4)                # sets y limits
ax.set_title('blabla')           # sets the axis title
ax.set(xlabel='bla')             # set multiple parameters at once
ax.legend(loc='upper center')    # activate legend
ax.grid(True, which='both')      # activate grid
bbox = ax.get_position()         # returns the axes bounding box
bbox.x0 + bbox.width             # bounding box parameters

### plotting routines

In [38]:
ax.plot(x,y, '-o', c='red', lw=2, label='bla')  # plots a line
ax.scatter(x,y, s=20, c=color)                  # scatter plot
ax.pcolormesh(xx,yy,zz, shading='gouraud')      # fast colormesh function
ax.colormesh(xx,yy,zz, norm=norm)               # slower colormesh function
ax.contour(xx,yy,zz, cmap='jet')                # contour line plot
ax.contourf(xx,yy,zz, vmin=2, vmax=4)           # filled contours plot
n, bins, patch = ax.hist(x, 50)                 # histogram
ax.imshow(matrix, origin='lower', extent=(x1, x2, y1, y2))  # show image
ax.specgram(y, FS=0.1, noverlap=128, scale='linear')  # plot a spectrogram

AttributeError: 'NoneType' object has no attribute 'plot'